[features]
seeds = false
skip-lint = false
[programs.localnet]
todo_list_app = "DBEwsLYQFHVoMqV2Q6qfwBSuWjipjT5dcNPmzeyp4oWy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/almei/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
